//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ass3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int userID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public int state { get; set; }
        public Nullable<int> postcode { get; set; }
        public int album { get; set; }
    
        public virtual States States { get; set; }
        public virtual Albums Albums { get; set; }
    }
}
